sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-qingdao.aliyuncs.com
    bucket-name: lzhgod
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}

  redis:
    host: localhost
    port: 6379
    #    password: 123456
    database: 0

# 引入机密配置文件（application-secrets.yml）
spring:
  profiles:
    include: secrets